spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
brevo:
  from:
    email: ${BREVO_FROM_EMAIL}
  api:
    key: ${BREVO_API_KEY}
